services:
  mayflix:
    build:
      context: .
      dockerfile: Dockerfile
    image: mayflix:latest
    restart: unless-stopped
    ports:
      - "5082:5082"
    environment:
      API_KEY: c1fdc69d31a262f799ca36915ef6f0bf
      ALLOWED_HOSTS: mayflix.sayitright.space
      DEBUG: "False"
      SECRET_KEY: django-secret-key
      TMDB_BASE_URL: https://api.themoviedb.org/3
      LANGUAGE: pt-BR


