services:
  mayflix:
    build:
      context: .
      dockerfile: Dockerfile
    image: mayflix:latest
    restart: unless-stopped
    ports:
      - "5082:5082"
    env_file:
      - .env
    entrypoint: >
      sh -c "python manage.py migrate --no-input &&
             python manage.py search_data &&
             gunicorn mayflix.wsgi:application --bind 0.0.0.0:5082 --workers 3"
