# Generated by Django 5.1 on 2024-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_tag_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='%(class)ss', to='core.movie'),
        ),
    ]
